// <auto-generated />
using System;
using GameDeals.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameDeals.Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.16");

            modelBuilder.Entity("GameDeals.Shared.Entities.CoverEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IGDBGameEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IGDBGameEntityId")
                        .IsUnique();

                    b.ToTable("Covers", (string)null);
                });

            modelBuilder.Entity("GameDeals.Shared.Entities.IGDBGameEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FirstReleaseDate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("GameDeals.Shared.Entities.PriceEntryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IGDBGameEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceNew")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IGDBGameEntityId");

                    b.ToTable("Prices", (string)null);
                });

            modelBuilder.Entity("GameDeals.Shared.Entities.CoverEntity", b =>
                {
                    b.HasOne("GameDeals.Shared.Entities.IGDBGameEntity", "Game")
                        .WithOne("Cover")
                        .HasForeignKey("GameDeals.Shared.Entities.CoverEntity", "IGDBGameEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameDeals.Shared.Entities.PriceEntryEntity", b =>
                {
                    b.HasOne("GameDeals.Shared.Entities.IGDBGameEntity", "Game")
                        .WithMany("Prices")
                        .HasForeignKey("IGDBGameEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameDeals.Shared.Entities.IGDBGameEntity", b =>
                {
                    b.Navigation("Cover");

                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
